package codeGeneration

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.PropertySpec
import indigo.Card
import indigo.Deck
import indigo.Rank
import indigo.Suit

object CardsGenerator {
    @JvmStatic
    fun main(args: Array<String>) = buildFileWithCardProperties().writeTo(System.out)

    private fun buildFileWithCardProperties() =
        FileSpec
            .builder(packageName = "indigo.generated.cards", fileName = "Cards.generated.kt")
            .addFileComment("Code generated by %S", "${this::class.simpleName}.kt")
            .addAnnotation(
                AnnotationSpec
                    .builder(Suppress::class)
                    .addMember("%S", "RedundantVisibilityModifier")
                    .addMember("%S", "unused")
                    .build()
            )
            .addImport(packageName = "indigo", Suit::class.simpleName!!, Rank::class.simpleName!!)
            .let {
                Deck
                    .allCards
                    .asSequence()
                    .map(::declareProperty)
                    .fold(initial = it) { builder, property -> builder.addProperty(property) }
            }
            .build()

    private fun declareProperty(card: Card) =
        PropertySpec
            .builder(name = "${card.rank.toString().lowercase()}Of${card.suit}", Card::class)
            .initializer(
                CodeBlock.of(
                    "${Card::class.simpleName}(${Suit::class.simpleName}.${card.suit}, ${Rank::class.simpleName}.${card.rank})"
                )
            )
            .build()

}
